#!/bin/zsh

function git_current_branch() {
  local ref
  ref=$(command git symbolic-ref --quiet HEAD 2> /dev/null)
  local ret=$?
  if [[ $ret != 0 ]]; then
    [[ $ret == 128 ]] && return  # no git repo.
    ref=$(command git rev-parse --short HEAD 2> /dev/null) || return
  fi
  echo ${ref#refs/heads/}
}

alias grep="grep --color=auto --exclude-dir={\*git,\*tox} "
alias ls="ls -hN --color=auto --group-directories-first"
alias size='ncdu -x'
alias gcm="make -s -j6 2>&1 | colout -t cmake | colout -t g++"
alias drive='/run/media/oguz/071E-7618'
alias h='htop'
alias rgrep='grep -r'
alias o='xdg-open &>/dev/null'
alias lrzconnect=' sudo openconnect -u ga53zeg  asa-cluster.lrz.de'
alias prime='ssh 10.149.72.194'
alias workstation='ssh -X 10.152.49.114'
alias alarm='ssh -X 192.168.1.74'
alias mountAlarm='sshfs 192.168.1.74:/home/oguz /home/oguz/pi'
alias cpuUsage="watch -n 1 'cat /proc/cpuinfo | grep "MHz"'"
alias pls="sudo"
alias trr="~/workspace/trr && n"
# alias confi3="vim ~/.config/i3/config"
alias cppsearch="grep --include=\*.{c,cpp,hpp,h} -rnw . -e "
alias findLatestChanged="find . -type f -exec stat --format '%Y :%y %n' "{}" \; | sort -nr | cut -d: -f2- | head"
alias zshrc="vim ~/.zshrc"
alias vimrc="vim ~/.vim/vimrc"
alias scs="maim -s ~/Pictures/$(date +%d%m%y%H%M%S).png"

##git
alias g='git'
alias gst='git status'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit -v'
alias gcmsg='git commit -m'
alias gdiff='git diff'
alias gd='git diff'
alias gf='git fetch'
alias ggpull='git pull origin "$(git_current_branch)"'
alias ggpush='git push origin "$(git_current_branch)"'

alias sauce="source ~/.zshrc && source ~/.zshenv"
alias py="python3.8"
alias p="pdflatex -interaction=nonstopmode -halt-on-error -synctex=1"
# alias yt="xclip -o | xargs -0 youtube-dl --add-metadata"
alias ka="killall"

# alias reconnect_eduroam="/home/oguz/./reconnect_to_eduroam"
alias headphoneConnect="bluetoothctl power on && bluetoothctl connect 38:18:4C:0E:67:C2"
alias headphoneDisconnect="bluetoothctl disconnect"
alias mv='mv -i' 
alias rm='rm -i'
alias cp='cp -iv'
# alias vtune="source /opt/intel/vtune_amplifier_2019.8.0.604197/amplxe-vars.sh && sudo /opt/intel/vtune_amplifier_2019/bin64/./amplxe-gui"
alias mountPlainDrive="udisksctl mount -b /dev/sda1"
alias mountEncrypted="udisksctl mount -b /dev/sda2"
alias v=$EDITOR
